### ISSUE TITLE
using a provider to manage state & data

### ISSUE THREAD

**Issue by tustoz** [tustoz/netflix_redesign#2]
This code does not use state management, so it is still messy to access various functions, methods, objects. and it's very inefficient and untidy. Therefore, I want to use a provider to manage state to make my code more efficient and well-organized.

*for anyone who wants to contribute, I really appreciate it

**Comment by pranavk05** [comment]
@tustoz  Hi I want to work with on this code

**Comment by tustoz** [comment]
> @tustoz  Hi I want to work with on this code 
> 

sure @pranavk05 please fork this project and give pull request to contribute.

**Comment by pranavk05** [comment]
@tustoz I have forked this project .Now what i have to do to get assigned?can you please help me with that as I'm new to open source

**Comment by pranavk05** [comment]
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/pranavkapoor/StudioProjects/netflix_redesign/build/app/outputs/flutter-apk/app.apk: 
Exception occurred while executing 'install':
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:557)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3143)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1341)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1303)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24747)
	at android.os.Binder.shellCommand(Binder.java:950)
	at and
Error launching application on sdk gphone64 arm64.
THIS ERROR IS COMING

**Comment by pranavk05** [comment]
@tustoz  I have solved the error now it is working on my local mac . can you please guide me what to do next?
